Pod & container level enhancements
stackpath/virtual-kubelet-stackpath pull request #12
Opened 2023-07-13 11:05 UTC by rolikoff

This PR adds support for new pod and container level fields that are supported by StackPath API.

Full list of new fields are: 
**Base level**
- initContainers
- hostAliases
- dnsConfig
- shareProcessNamespace

**Container's level**
- imagePullPolicy
- args
- workingDir
- lifecycle
- terminationMessagePath
- terminationMessagePolicy
- startupProbe
- terminationGracePeriodSeconds

2023-07-13 12:46 UTC, denis-adamcho approved these changes
LGTM

2023-07-16 08:06 UTC, shayrybak requested changes

2023-07-16 08:06 UTC, shayrybak commented on internal/provider/workload_translation.go
> +		settings.TerminationGracePeriodSeconds = strconv.FormatInt(int64(*spec.TerminationGracePeriodSeconds), 10)
can this operation fail? if so should we handle that error case?

2023-07-16 08:06 UTC, shayrybak commented on internal/provider/workload_translation.go
> +		p.logger.Info("exec container lifecycle is not supported, skipping")
probably should be a warning level

2023-07-17 15:15 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		p.logger.Info("exec container lifecycle is not supported, skipping")
Updated here and in a few more places.

2023-07-17 15:29 UTC, rolikoff commented on README.md
> +- **Lifecycle's PostStart**. The `postStart` hook in the lifecycle should only be used when the container is expected to start immediately. However, in most cases, this hook fails when using `httpGet
Updated.

2023-07-26 06:00 UTC, shayrybak commented
@rolikoff can we please add all the new fields that are supported to the readme?

2023-08-30 13:22 UTC, shayrybak approved these changes

2023-08-30 13:23 UTC, merged