Security context support
stackpath/virtual-kubelet-stackpath pull request #13
Opened 2023-07-18 10:46 UTC by rolikoff

Enhances support for security context at both the pod and container levels. While not all fields are currently supported, the following is a list of those that are:

**Pod/Instance level**
- runAsUser
- runAsGroup
- runAsNonRoot: true
- supplementalGroups
- sysctls

**Container level**
- runAsUser
- runAsGroup
- runAsNonRoot
- allowPrivilegeEscalation
- capabilities

2023-07-24 07:22 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		})
If that happens, the workload will be created but the instance will not run. I don't think its a good idea to validate sysctls on the vk provider's side. IMO, we have to bypass whatever users provide, but let the users know what we currently support based on the current kernel's version.

2023-07-24 15:10 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		})
Verified with the API team, they have implemented the validation on the API side recently. I have double checked that, was trying to create a new pod with `kernel.shmni` sysctl, got `Invalid workload specification: workload.spec.runtime.containers.securityContext.sysctls: Forbidden: unsupported sysctls kernel.shmmni` response.

2023-07-25 08:01 UTC, shayrybak approved these changes

2023-08-20 08:21 UTC, shayrybak requested changes

2023-08-20 08:21 UTC, shayrybak commented on internal/provider/workload_translation.go
> +		p.logger.Info("!!!!!!!!!!!!!")
leftovers?

2023-08-20 08:26 UTC, shayrybak approved these changes

2023-08-30 13:17 UTC, merged