Adds new geometrics support
stackpath/virtual-kubelet-stackpath pull request #14
Opened 2023-08-25 20:16 UTC by rolikoff

Adds new SP-6, SP-7, SP-8 geometrics support. 

The following table represents newly added geometrics.

| Subscription | Cores | RAM   |
|--------------|-------|--------|
| SP-6         | 16    | 64GiB  |
| SP-7         | 32    | 128GiB |
| SP-8         | 48    | 256GiB |

2023-08-25 23:00 UTC, ds93math requested changes

2023-08-25 23:00 UTC, ds93math commented on internal/provider/workload_translation_test.go
> +		},
@shayrybak @rolikoff can we include unit tests that "if there is small CPU resource, not enough memory for SP-(n), will result in SP-(n+1)"

For example, client requests 40 GiB RAM. Auto-upgrade/translate from SP-5 --> SP-6.

2023-08-26 05:12 UTC, rolikoff commented on internal/provider/constants.go
> +	containerResourcesSP8 = workload_models.V1StringMapEntry{"cpu": "64", "memory": "256Gi"}
good catch, thank you.  Updated

2023-08-26 05:12 UTC, rolikoff commented on internal/provider/workload_translation.go
> +	mem128Gi := resource.NewQuantity(128*oneGi, resource.BinarySI)
Not really, since SP-8 is the largest geometry, all that is more than SP-7 CPU (32 core) and memory (128G) falls under SP-8. Thus we don't need an additional quantity variable to check this case.

2023-08-26 05:13 UTC, rolikoff commented on internal/provider/workload_translation.go
> +	cpu32 := resource.NewQuantity(32, resource.DecimalSI)
Same as above.

2023-08-26 05:15 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		return containerResourcesSP8
This is a cmp operation: `Cmp returns 0 if the quantity is equal to y, -1 if the quantity is less than y, or 1 if the quantity is greater than y.` So that really means "if CPU > 32 or mem > 128 then return SP8"

2023-08-26 05:18 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		return containerResourcesSP7
This particular logic checks "if (CPU > 16 AND CPU <= 32) OR (mem > 64 AND mem <=128) then return SP7". As in the comment above, please notice that this is a `cmp` operation.

2023-08-26 05:19 UTC, rolikoff commented on internal/provider/workload_translation.go
> +		return containerResourcesSP6
Please see the comment above

2023-08-26 05:19 UTC, rolikoff commented on internal/provider/workload_translation.go
>  		return containerResourcesSP5
Please see the comment above

2023-08-26 05:44 UTC, rolikoff commented on internal/provider/workload_translation.go
I've checked this once again, looks good. The `cmp` could be confusing sometimes, hence unit tests help a lot :) We have 100% coverage for this logic.

2023-08-26 06:12 UTC, rolikoff commented on internal/provider/workload_translation_test.go
> +		},
Currently, the VK provider lacks support for pod updates, limiting the invocation of toSPInstanceSize() solely to pod creation instances. The chosen geometry appropriately aligns with the resource requests/limits specified in the podspec file. This selection process is thoroughly validated by existing unit tests. For instance, if a user specifies a request for 40G RAM and a configuration with fewer than 16 cores, the system will intelligently opt for SP-6. I have added a specific case that validates that SP-6 will be selected if the CPU requirement is low with the memory requirement == 40GiB. I have also updated the unit test descriptions, hopefully this will be a bit more clearer now.

2023-08-27 07:42 UTC, shayrybak approved these changes

2023-08-28 14:49 UTC, ds93math commented on internal/provider/workload_translation.go
understood, sounds good. thanks for taking another look!

2023-08-28 14:51 UTC, ds93math approved these changes
No additional comments or issues with changes/updates made. Thanks for everyone's timely responses.

2023-08-30 13:09 UTC, merged