Adds support for Run a command in a container
stackpath/virtual-kubelet-stackpath pull request #3
Opened 2023-06-06 19:53 UTC by rolikoff

This PR implements RunInContainer method of the `Provider` interface. It gives an ability to run commands inside your pods. 

The readme file was updated with the additional information about this new feature.

2023-06-07 12:40 UTC, shayrybak approved these changes
LGTM

2023-06-07 12:40 UTC, shayrybak commented on deployment/kustomize/base/kustomization.yaml
> +  newTag: v0.1.0
let's update this to v0.2.0 for so it will be relevant to the release

2023-06-07 15:16 UTC, rolikoff commented on deployment/kustomize/base/kustomization.yaml
> +  newTag: v0.1.0
Updated.

2023-06-07 15:16 UTC, rolikoff commented on deployment/kustomize/base/vk-deployment.yaml
> +    image: ghcr.io/stackpath/virtual-kubelet-stackpath:v0.1.0
Updated.

2023-06-07 15:20 UTC, shayrybak approved these changes

2023-06-07 20:51 UTC, brentahughes commented on cmd/virtual-kubelet/main.go
> +			p, err := spprovider.NewStackpathProvider(ctx, stackpathClient, apiConfig, cfg, os.Getenv("VKUBELET_POD_IP"), listenPort)
This error isn't handled until after its already called `ConfigureNode`. This could cause a potential nil pointer panic.

2023-06-07 20:51 UTC, brentahughes commented on internal/provider/container_runner.go
> +				time.Sleep(time.Millisecond * 50)
Instead of blocking with a sleep we should use an After channel. 

```go
for {
  select {
    ...
  case <-time.After(time.Millisecond * 50):
    continue 
  }
}
```

2023-06-08 11:55 UTC, rolikoff commented on cmd/virtual-kubelet/main.go
> +			p, err := spprovider.NewStackpathProvider(ctx, stackpathClient, apiConfig, cfg, os.Getenv("VKUBELET_POD_IP"), listenPort)
Thanks. Updated.

2023-06-08 11:55 UTC, rolikoff commented on internal/provider/container_runner.go
> +				time.Sleep(time.Millisecond * 50)
Updated.

2023-06-08 14:30 UTC, drrev requested changes
Looks good over all, just a few minor changes.

2023-06-08 14:30 UTC, drrev commented on internal/provider/provider.go
> +	containerConsolePort int32
Should this be `uint16`?

2023-06-09 13:36 UTC, rolikoff commented on internal/provider/provider.go
> +	daemonEndpointPort   int32
k8s package expects int32, so there's no really need to change that https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5220

2023-06-09 13:45 UTC, rolikoff commented on internal/provider/provider.go
> +		HostKeyCallback: ssh.HostKeyCallback(func(hostname string, remote net.Addr, key ssh.PublicKey) error { return nil }),
Agree, we might let the users to configure the path to their known_hosts file via env var or conf.

2023-06-09 21:51 UTC, drrev requested changes

2023-06-09 21:51 UTC, drrev commented on internal/provider/container_runner.go
> +				return ctx.Err()
The lingering design issue I see here is dealing with cancellation on the context passed into `Exec`. Currently, there isn't anything to interrupt the command running under `session.Run`.

One approach is `session.Signal`, but I have had some issues with it in the past. That may no longer be the case, but some testing should be done.

Since you are requesting a pseudo TTY, any child process should die when the session is closed, so closing session early should work to kill any running commands.

There are a few different approaches to handle this, but closing the session here may be sufficient. You will need to test various scenarios to ensure that approach functions properly (processes are indeed killed on the target, etc.), but the parent context being cancelled should cascade and cause this case to run.

2023-06-12 16:31 UTC, rolikoff commented on internal/provider/container_runner.go
> +				return ctx.Err()
Thanks. That makes sense. I have completely missed that case. Added session.close() line here.

2023-06-12 16:32 UTC, rolikoff commented
@drrev 
The PR was updated with additional fix for a case where a user closes the terminal window. I couldn't find a better solution rather than checking if the window width/height is 0/0. It looks like the VK lib doesn't cancel the context if a user closes the terminal. IMO that should be handled by the library. I will ask VK team about that.

2023-06-13 01:11 UTC, drrev commented on internal/provider/container_runner.go
> +				return ctx.Err()
Might need to look into some integration tests to make sure that all test cases are covered.

Resolving as you have addressed my immediate concerns.

2023-06-13 01:31 UTC, drrev commented
> @drrev The PR was updated with additional fix for a case where a user closes the terminal window. I couldn't find a better solution rather than checking if the window width/height is 0/0. It looks like the VK lib doesn't cancel the context if a user closes the terminal. IMO that should be handled by the library. I will ask VK team about that.

There should definitely be a way to register an on-close callback or at least a way to check if the terminal window is closed. Checking for `0,0` could potentially cause issues, depending on how sizing is handled. Hopefully the VK team has an answer.

2023-06-13 13:40 UTC, drrev commented on internal/provider/container_runner.go
> +	defer session.Close()
Would the double close cause any issues? I checked [the source code](https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.10.0:ssh/channel.go;l=547-554); it looks like this may be fine, assuming that sending close causes `ch.decided  = true`.

2023-06-14 07:09 UTC, rolikoff commented on internal/provider/container_runner.go
> +	defer session.Close()
No, double close doesn't cause any issues. I have checked that case specifically.

2023-06-14 13:28 UTC, drrev approved these changes
LGTM

2023-06-14 14:44 UTC, drrev commented on internal/provider/container_runner.go
> +		err = session.RequestPty("Xterm", 120, 60, modes)
This argument is just setting the TERM env var for the session, which is explained in depth [here](https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html). So, the arg would set `TERM=Xterm` (unsure on case sensitivity here, so may need to be changed to `xterm`) as the format for session output--as in the format that we expect to receive from the session is xterm format.

2023-06-15 12:12 UTC, merged